permalink: /discover/:year/:month/:day/:title.html

xcsoar_stable_version: '7.27'
xcsoar_testing_version: null
xcsoar_old_version: '7.26'

server_url: ''
absolute_server_url: '//xcsoar.org'
download_server_url: 'https://download.xcsoar.org/releases'
trac_server_url: 'https://github.com/XCSoar/XCSoar/issues'
mapgen_url: 'http://mapgen.xcsoar.org/'

plugins:
  - jekyll/minibundle
