permalink: /discover/:year/:month/:day/:title.html

xcsoar_stable_version: 6.8.11
xcsoar_testing_version: null
xcsoar_old_version: 6.8.10

server_url: ''
absolute_server_url: '//www.xcsoar.org'
download_server_url: 'http://download.xcsoar.org/releases'
trac_server_url: 'https://bugs.xcsoar.org'
mapgen_url: 'http://mapgen.xcsoar.org/'

asset_bundler:
  cdn: '//www.xcsoar.org'
  compress:
    css: 'yui-compressor --type css'
    js: 'yui-compressor --type js'
  markup_templates:
    js: "<script type='text/javascript' src='{{url}}'> </script>\n"
